spring.application.name=jeux

spring.datasource.url=jdbc:mysql://localhost:3306/jeux_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

logging.level.root=OFF